In [11]:
!pip install yfinance==0.1.67
!pip install beautifulsoup4
!pip install nbformat==4.2.0
!pip install plotly==5.13.1
!pip install html5lib

Requirement already satisfied: yfinance==0.1.67 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (0.1.67)
Requirement already satisfied: multitasking>=0.0.7 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from yfinance==0.1.67) (0.0.11)
Requirement already satisfied: numpy>=1.15 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from yfinance==0.1.67) (1.20.3)
Requirement already satisfied: pandas>=0.24 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from yfinance==0.1.67) (1.3.3)
Requirement already satisfied: requests>=2.20 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from yfinance==0.1.67) (2.25.1)
Requirement already satisfied: lxml>=4.5.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from yfinance==0.1.67) (4.9.2)
Requirement already satisfied: python-dateutil>=2.7.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from pandas>=0.24->yfinance==0.1.67) (2021.1)
Requirement already satisfied: idna<3,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (1.26.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.20->yfinance==0.1.67) (2021.5.30)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas>=0.24->yfinance==0.1.67) (1.15.0)
Requirement already satisfied: beautifulsoup4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (4.11.2)
Requirement already satisfied: soupsieve>1.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from beautifulsoup4) (2.4)
Requirement already satisfied: nbformat==4.2.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (4.2.0)
Requirement already satisfied: traitlets>=4.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from nbformat==4.2.0) (5.9.0)
Requirement already satisfied: jupyter-core in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from nbformat==4.2.0) (4.12.0)
Requirement already satisfied: ipython-genutils in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from nbformat==4.2.0) (0.2.0)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from nbformat==4.2.0) (4.17.3)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (0.19.3)
Requirement already satisfied: attrs>=17.4.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (22.2.0)
Requirement already satisfied: importlib-metadata in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (4.0.1)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (1.3.10)
Requirement already satisfied: typing-extensions in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (3.7.4.3)
Requirement already satisfied: importlib-resources>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (5.12.0)
Requirement already satisfied: zipp>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from importlib-resources>=1.4.0->jsonschema!=2.5.0,>=2.4->nbformat==4.2.0) (3.4.1)
Requirement already satisfied: plotly==5.13.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (5.13.1)
Requirement already satisfied: tenacity>=6.2.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from plotly==5.13.1) (8.2.2)
Requirement already satisfied: html5lib in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (1.1)
Requirement already satisfied: webencodings in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from html5lib) (0.5.1)
Requirement already satisfied: six>=1.9 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from html5lib) (1.15.0)

In [13]:
import yfinance as yf
import pandas as pd
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [14]:
tesla = yf.Ticker("TSLA")

In [15]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"
tesla_data = requests.get(url).text

In [20]:
soup = BeautifulSoup(tesla_data,"html.parser")

In [35]:
tesla_rev = pd.DataFrame(columns=['Date','Revenue'])

In [36]:
print(soup.find_all("tbody"))

[<tbody>
<tr>
<td style="text-align:center">2021</td>
<td style="text-align:center">$53,823</td>
</tr>
<tr>
<td style="text-align:center">2020</td>
<td style="text-align:center">$31,536</td>
</tr>
<tr>
<td style="text-align:center">2019</td>
<td style="text-align:center">$24,578</td>
</tr>
<tr>
<td style="text-align:center">2018</td>
<td style="text-align:center">$21,461</td>
</tr>
<tr>
<td style="text-align:center">2017</td>
<td style="text-align:center">$11,759</td>
</tr>
<tr>
<td style="text-align:center">2016</td>
<td style="text-align:center">$7,000</td>
</tr>
<tr>
<td style="text-align:center">2015</td>
<td style="text-align:center">$4,046</td>
</tr>
<tr>
<td style="text-align:center">2014</td>
<td style="text-align:center">$3,198</td>
</tr>
<tr>
<td style="text-align:center">2013</td>
<td style="text-align:center">$2,013</td>
</tr>
<tr>
<td style="text-align:center">2012</td>
<td style="text-align:center">$413</td>
</tr>
<tr>
<td style="text-align:center">2011</td>
<td style="text-align:center">$204</td>
</tr>
<tr>
<td style="text-align:center">2010</td>
<td style="text-align:center">$117</td>
</tr>
<tr>
<td style="text-align:center">2009</td>
<td style="text-align:center">$112</td>
</tr>
</tbody>, <tbody>
<tr>
<td style="text-align:center">2022-09-30</td>
<td style="text-align:center">$21,454</td>
</tr>
<tr>
<td style="text-align:center">2022-06-30</td>
<td style="text-align:center">$16,934</td>
</tr>
<tr>
<td style="text-align:center">2022-03-31</td>
<td style="text-align:center">$18,756</td>
</tr>
<tr>
<td style="text-align:center">2021-12-31</td>
<td style="text-align:center">$17,719</td>
</tr>
<tr>
<td style="text-align:center">2021-09-30</td>
<td style="text-align:center">$13,757</td>
</tr>
<tr>
<td style="text-align:center">2021-06-30</td>
<td style="text-align:center">$11,958</td>
</tr>
<tr>
<td style="text-align:center">2021-03-31</td>
<td style="text-align:center">$10,389</td>
</tr>
<tr>
<td style="text-align:center">2020-12-31</td>
<td style="text-align:center">$10,744</td>
</tr>
<tr>
<td style="text-align:center">2020-09-30</td>
<td style="text-align:center">$8,771</td>
</tr>
<tr>
<td style="text-align:center">2020-06-30</td>
<td style="text-align:center">$6,036</td>
</tr>
<tr>
<td style="text-align:center">2020-03-31</td>
<td style="text-align:center">$5,985</td>
</tr>
<tr>
<td style="text-align:center">2019-12-31</td>
<td style="text-align:center">$7,384</td>
</tr>
<tr>
<td style="text-align:center">2019-09-30</td>
<td style="text-align:center">$6,303</td>
</tr>
<tr>
<td style="text-align:center">2019-06-30</td>
<td style="text-align:center">$6,350</td>
</tr>
<tr>
<td style="text-align:center">2019-03-31</td>
<td style="text-align:center">$4,541</td>
</tr>
<tr>
<td style="text-align:center">2018-12-31</td>
<td style="text-align:center">$7,226</td>
</tr>
<tr>
<td style="text-align:center">2018-09-30</td>
<td style="text-align:center">$6,824</td>
</tr>
<tr>
<td style="text-align:center">2018-06-30</td>
<td style="text-align:center">$4,002</td>
</tr>
<tr>
<td style="text-align:center">2018-03-31</td>
<td style="text-align:center">$3,409</td>
</tr>
<tr>
<td style="text-align:center">2017-12-31</td>
<td style="text-align:center">$3,288</td>
</tr>
<tr>
<td style="text-align:center">2017-09-30</td>
<td style="text-align:center">$2,985</td>
</tr>
<tr>
<td style="text-align:center">2017-06-30</td>
<td style="text-align:center">$2,790</td>
</tr>
<tr>
<td style="text-align:center">2017-03-31</td>
<td style="text-align:center">$2,696</td>
</tr>
<tr>
<td style="text-align:center">2016-12-31</td>
<td style="text-align:center">$2,285</td>
</tr>
<tr>
<td style="text-align:center">2016-09-30</td>
<td style="text-align:center">$2,298</td>
</tr>
<tr>
<td style="text-align:center">2016-06-30</td>
<td style="text-align:center">$1,270</td>
</tr>
<tr>
<td style="text-align:center">2016-03-31</td>
<td style="text-align:center">$1,147</td>
</tr>
<tr>
<td style="text-align:center">2015-12-31</td>
<td style="text-align:center">$1,214</td>
</tr>
<tr>
<td style="text-align:center">2015-09-30</td>
<td style="text-align:center">$937</td>
</tr>
<tr>
<td style="text-align:center">2015-06-30</td>
<td style="text-align:center">$955</td>
</tr>
<tr>
<td style="text-align:center">2015-03-31</td>
<td style="text-align:center">$940</td>
</tr>
<tr>
<td style="text-align:center">2014-12-31</td>
<td style="text-align:center">$957</td>
</tr>
<tr>
<td style="text-align:center">2014-09-30</td>
<td style="text-align:center">$852</td>
</tr>
<tr>
<td style="text-align:center">2014-06-30</td>
<td style="text-align:center">$769</td>
</tr>
<tr>
<td style="text-align:center">2014-03-31</td>
<td style="text-align:center">$621</td>
</tr>
<tr>
<td style="text-align:center">2013-12-31</td>
<td style="text-align:center">$615</td>
</tr>
<tr>
<td style="text-align:center">2013-09-30</td>
<td style="text-align:center">$431</td>
</tr>
<tr>
<td style="text-align:center">2013-06-30</td>
<td style="text-align:center">$405</td>
</tr>
<tr>
<td style="text-align:center">2013-03-31</td>
<td style="text-align:center">$562</td>
</tr>
<tr>
<td style="text-align:center">2012-12-31</td>
<td style="text-align:center">$306</td>
</tr>
<tr>
<td style="text-align:center">2012-09-30</td>
<td style="text-align:center">$50</td>
</tr>
<tr>
<td style="text-align:center">2012-06-30</td>
<td style="text-align:center">$27</td>
</tr>
<tr>
<td style="text-align:center">2012-03-31</td>
<td style="text-align:center">$30</td>
</tr>
<tr>
<td style="text-align:center">2011-12-31</td>
<td style="text-align:center">$39</td>
</tr>
<tr>
<td style="text-align:center">2011-09-30</td>
<td style="text-align:center">$58</td>
</tr>
<tr>
<td style="text-align:center">2011-06-30</td>
<td style="text-align:center">$58</td>
</tr>
<tr>
<td style="text-align:center">2011-03-31</td>
<td style="text-align:center">$49</td>
</tr>
<tr>
<td style="text-align:center">2010-12-31</td>
<td style="text-align:center">$36</td>
</tr>
<tr>
<td style="text-align:center">2010-09-30</td>
<td style="text-align:center">$31</td>
</tr>
<tr>
<td style="text-align:center">2010-06-30</td>
<td style="text-align:center">$28</td>
</tr>
<tr>
<td style="text-align:center">2010-03-31</td>
<td style="text-align:center">$21</td>
</tr>
<tr>
<td style="text-align:center">2009-12-31</td>
<td style="text-align:center"></td>
</tr>
<tr>
<td style="text-align:center">2009-09-30</td>
<td style="text-align:center">$46</td>
</tr>
<tr>
<td style="text-align:center">2009-06-30</td>
<td style="text-align:center">$27</td>
</tr>
</tbody>, <tbody>
<tr>
<td style="text-align:center"><a href="https://www.macrotrends.net/stocks/sector/5/auto-tires-trucks">Auto/Tires/Trucks</a></td>
<td style="text-align:center"><a href="https://www.macrotrends.net/stocks/industry/7/">Auto Manufacturers - Domestic</a></td>
<td style="text-align:center">$549.575B</td>
<td style="text-align:center">$53.823B</td>
</tr>
<tr>
<td colspan="4" style="padding:15px;">
<span>Tesla is the market leader in battery-powered electric car sales in the United States, with roughly 70% market share. The company's flagship Model 3 is the best-selling EV model in the United States. Tesla, which has managed to garner the reputation of a gold standard over the years, is now a far bigger entity that what it started off since its IPO in 2010, with its market cap crossing $1 trillion for the first time in October 2021.? The EV king's market capitalization is more than the combined value of legacy automakers including Toyota, Volkswagen, Daimler, General Motors and Ford.Over the years, Tesla has shifted from developing niche products for affluent buyers to making more affordable EVs for the masses. The firm's three-pronged business model approach of direct sales, servicing, and charging its EVs sets it apart from other carmakers. Tesla, which is touted as the clean energy revolutionary automaker, is much more than just a car manufacturer.</span>
</td>
</tr>
</tbody>, <tbody>
<tr>
<td style="text-align:left"><a href="/stocks/charts/GM/general-motors/revenue">General Motors (GM)</a></td>
<td style="text-align:center">United States</td>
<td style="text-align:center">$53.930B</td>
<td style="text-align:center">5.56</td>
</tr>
<tr>
<td style="text-align:left"><a href="/stocks/charts/F/ford-motor/revenue">Ford Motor (F)</a></td>
<td style="text-align:center">United States</td>
<td style="text-align:center">$52.668B</td>
<td style="text-align:center">8.09</td>
</tr>
<tr>
<td style="text-align:left"><a href="/stocks/charts/HOG/harley-davidson/revenue">Harley-Davidson (HOG)</a></td>
<td style="text-align:center">United States</td>
<td style="text-align:center">$6.762B</td>
<td style="text-align:center">9.56</td>
</tr>
<tr>
<td style="text-align:left"><a href="/stocks/charts/PII/polaris/revenue">Polaris (PII)</a></td>
<td style="text-align:center">United States</td>
<td style="text-align:center">$6.267B</td>
<td style="text-align:center">11.86</td>
</tr>
<tr>
<td style="text-align:left"><a href="/stocks/charts/IAA/iaa/revenue">IAA (IAA)</a></td>
<td style="text-align:center">United States</td>
<td style="text-align:center">$5.134B</td>
<td style="text-align:center">16.40</td>
</tr>
<tr>
<td style="text-align:left"><a href="/stocks/charts/FSR/fisker/revenue">Fisker (FSR)</a></td>
<td style="text-align:center">United States</td>
<td style="text-align:center">$2.261B</td>
<td style="text-align:center">0.00</td>
</tr>
<tr>
<td style="text-align:left"><a href="/stocks/charts/LEV/lion-electric/revenue">Lion Electric (LEV)</a></td>
<td style="text-align:center">Canada</td>
<td style="text-align:center">$0.551B</td>
<td style="text-align:center">0.00</td>
</tr>
<tr>
<td style="text-align:left"><a href="/stocks/charts/VLTA/volta/revenue">Volta (VLTA)</a></td>
<td style="text-align:center">United States</td>
<td style="text-align:center">$0.071B</td>
<td style="text-align:center">0.00</td>
</tr>
<tr>
<td style="text-align:left"><a href="/stocks/charts/BRDS/bird-global/revenue">Bird Global (BRDS)</a></td>
<td style="text-align:center">United States</td>
<td style="text-align:center">$0.054B</td>
<td style="text-align:center">0.00</td>
</tr>
<tr>
<td style="text-align:left"><a href="/stocks/charts/ZEV/lightning-emotors/revenue">Lightning EMotors (ZEV)</a></td>
<td style="text-align:center">United States</td>
<td style="text-align:center">$0.043B</td>
<td style="text-align:center">0.00</td>
</tr>
</tbody>, <tbody>
<tr>
<td><a>Tesla Revenue 2010-2022 | TSLA</a></td>
<td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Tesla Revenue 2010-2022 | TSLA&lt;/a&gt;"/></td>
</tr>
<tr>
<td><a>Macrotrends</a></td>
<td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Macrotrends&lt;/a&gt;"/></td>
</tr>
<tr>
<td><a>Source</a></td>
<td><input class="modal_link" size="60" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Source&lt;/a&gt;"/></td>
</tr>
</tbody>, <tbody>
<tr>
<td><a>Tesla Revenue 2010-2022 | TSLA</a></td>
<td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Tesla Revenue 2010-2022 | TSLA&lt;/a&gt;"/></td>
</tr>
<tr>
<td><a>Macrotrends</a></td>
<td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Macrotrends&lt;/a&gt;"/></td>
</tr>
<tr>
<td><a>Source</a></td>
<td><input class="modal_link" size="50" type="text" value="&lt;a href='https://www.macrotrends.net/stocks/charts/TSLA/tesla/revenue'&gt;Source&lt;/a&gt;"/></td>
</tr>
</tbody>]

In [37]:
for row in soup.find_all("tbody")[1].find_all("tr"):
    col = row.find_all("td")
    date = col[0].text
    rev = col[1].text
    tesla_rev = tesla_rev.append({
        "Date": date,
        "Revenue":rev
    },ignore_index=True)
tesla_rev.head()

         Date  Revenue
0  2022-09-30  $21,454
1  2022-06-30  $16,934
2  2022-03-31  $18,756
3  2021-12-31  $17,719
4  2021-09-30  $13,757

In [48]:
tesla_rev["Revenue"] = tesla_rev["Revenue"].replace(r"\$|,","",regex=True)

In [49]:
tesla_rev.head()

         Date Revenue
0  2022-09-30   21454
1  2022-06-30   16934
2  2022-03-31   18756
3  2021-12-31   17719
4  2021-09-30   13757

In [50]:
gme = yf.Ticker('GME')
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/stock.html"

html_data  = requests.get(url).text

In [51]:
soup = BeautifulSoup(html_data,"html.parser")

In [52]:
gme_df = pd.DataFrame(columns=["Date","Revenue"])

In [53]:
for row in soup.find_all("tbody")[1].find_all("tr"):
    col = row.find_all("td")
    date = col[0].text
    rev = col[1].text
    gme_df = gme_df.append({
        "Date": date,
        "Revenue":rev
    },ignore_index=True)
gme_df.head()

         Date Revenue
0  2020-04-30  $1,021
1  2020-01-31  $2,194
2  2019-10-31  $1,439
3  2019-07-31  $1,286
4  2019-04-30  $1,548

In [54]:
gme_df["Revenue"] = gme_df["Revenue"].replace(r"\$|,","",regex=True)

In [55]:
gme_df.head()

         Date Revenue
0  2020-04-30    1021
1  2020-01-31    2194
2  2019-10-31    1439
3  2019-07-31    1286
4  2019-04-30    1548